export 'dart:convert';
export 'dart:io';

export 'package:dio/dio.dart';
export 'package:firebase_core/firebase_core.dart';
export 'package:firebase_messaging/firebase_messaging.dart';
export 'package:flutter/foundation.dart';
export 'package:flutter/material.dart';
export 'package:flutter/services.dart';
export 'package:flutter_svg/flutter_svg.dart';
export 'package:fluttertoast/fluttertoast.dart';
export 'package:go_router/go_router.dart';
export 'package:hexcolor/hexcolor.dart';
export 'package:loading_indicator/loading_indicator.dart';
export 'package:package_info_plus/package_info_plus.dart';
export 'package:percent_indicator/percent_indicator.dart';
export 'package:provider/provider.dart';
export 'package:reuse/reuse_widgets.dart';
export 'package:smine/smine_widgets.dart';
export 'package:sunmi/sunmi_widgets.dart';

// export 'package:sunmi_printer/sunmi_printer.dart';

export 'src/alerts/alert_dialog.dart';
export 'src/database/localDB.dart';
// export 'src/database/original/localDB.dart';
export 'src/firebase/firebase_api.dart';
export 'src/login/auth/web_login.dart';
export 'src/login/web/repository/login_repository.dart';
export 'src/login/web/repository/original/login_repository.dart';
export 'src/login/web/view_model/login_view_model.dart';
export 'src/login/web/web_version_login.dart';
export 'src/login/web_utils.dart';
export 'src/main/main_page.dart';
export 'src/model/access_token.dart';
export 'src/model/user_info.dart';
export 'src/mvvm/api/api_service.dart';
export 'src/mvvm/model/user_model.dart';
export 'src/mvvm/provider/multi_provider.dart';
export 'src/mvvm/repository/main_repository.dart';
export 'src/mvvm/response_api.dart';
export 'src/mvvm/viewModel/main_view_model.dart';
export 'src/navigation/navigator.dart';
export 'src/notification/notification_screen.dart';
export 'src/notification/utils/notification_utils.dart';
export 'src/shimmer/shimmer_screen.dart';
export 'src/splash/splash_page.dart';
export 'src/transitions/custom_page_route.dart';
export 'src/transitions/page_transition.dart';
export 'src/ui/widget_controller.dart';
export 'src/utils/app_url.dart';
export 'src/utils/colors.dart';
export 'src/utils/constants.dart';
export 'src/utils/custom_back_button.dart';
export 'src/utils/debouncer.dart';
export 'src/utils/graphQL.dart';
export 'src/utils/strings.dart';
