name: common
description: A new Flutter package project.
version: 1.0.0+1
publish_to: none

environment:
  sdk: '>=3.0.5 <4.0.0'
  flutter: ">=3.10.5"

dependencies:
  flutter:
    sdk: flutter
  shared_preferences: ^2.2.3
  loading_indicator: ^3.1.1
  hexcolor: ^3.0.1
  shimmer: ^3.0.0
  fluttertoast: ^8.2.6
#  get: ^4.6.5
  get: ^4.6.6
  animations: ^2.0.11
  flutter_svg: ^2.0.10+1
  badges: ^3.1.2
  firebase_messaging: ^15.0.2
  package_info_plus: ^8.0.0
  firebase_core: ^3.2.0
  percent_indicator: ^4.2.3
  webview_flutter: ^4.8.0
  dio: ^5.5.0+1
  provider: ^6.1.2
  go_router: ^14.2.1
  intl: ^0.19.0
  uuid: ^4.4.2
  qr_code_scanner: ^1.0.1
  mobile_scanner: ^5.1.1

  #  rfid_c72_plugin: ^0.0.2
#  uhf_c72_plugin: ^1.0.1
  graphql_flutter: ^5.1.2
  sunmi_printer_plus: ^2.1.3
  esc_pos_utils: ^1.1.0
  qr_flutter: ^4.1.0

#  json_annotation: ^4.9.0
#  freezed: ^2.5.2
#  freezed_annotation: ^2.4.3






  smine:
    path: ../smine
  sunmi:
    path: ../sunmi
  reuse:
    path: ../reuse



dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
#  build_runner: ^2.4.11
#  json_serializable: ^6.8.0


# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:

  uses-material-design: true
  assets:
    - assets/images/

  fonts:
    - family: Inter
      fonts:
        - asset: assets/fonts/Inter-Regular.ttf
        - asset: assets/fonts/Inter-Medium.ttf
        - asset: assets/fonts/Inter-Bold.ttf

  # To add assets to your package, add an assets section, like this:
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg
  #
  # For details regarding assets in packages, see
  # https://flutter.dev/assets-and-images/#from-packages
  #
  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware

  # To add custom fonts to your package, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts in packages, see
  # https://flutter.dev/custom-fonts/